security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
               users:
                   admin:
                       password: $2y$12$T/Ta0gzV60hPRrsv2Peyeu8DUFmMmjGpO7H0rO0wwUgnIWmiIwgl2
                       roles: 'ROLE_ADMIN'
        user_provider:
                   entity:
                       class: App\Entity\User
                       property: username


        all_providers:
            chain:
                providers: [ in_memory, user_provider]

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: all_providers
            anonymous: ~
            # activate different ways to authenticate
            #http_basic: ~
            form_login:
                login_path: app.security.login
                check_path: app.security.login
                default_target_path: app.security.redirect

            logout:
                path: app.security.logout
                target : app.homepage

    access_control:
            # require ROLE_ADMIN for /admin
            - { path: ^/admin, roles: ROLES_ADMIN }
            - { path: ^/admin/, roles: ROLES_ADMIN }
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            # form_login: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
